# 🛒 E-commerce Customer Data Cleaning & Preparation
**Author:** Ali Ashrafi | **GitHub:** [@ali-ashrafi](https://github.com/ali-ashrafi)  
**Tools:** Python, Pandas, NumPy, Jupyter Notebook  

---

### 🎯 Project Objective
The objective of this project is to inspect, clean, validate, and prepare a raw e-commerce customer dataset for downstream analytics and predictive modeling.

## 1. Overview & Setup

In [1]:
# libreries

import pandas as pd
import numpy as np
import sys
import openpyxl

In [2]:
# versions

print(f'Python version is : {sys.version}')
print(f'Pandas version is : {pd.__version__}')
print(f'Numpy version is : {np.__version__}')

Python version is : 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Pandas version is : 2.2.3
Numpy version is : 2.2.2

## 2.Data ingestion & initial profiling

In [4]:
data = pd.read_excel (r'F:\StudyBuilt\ali-ashrafi\data\raw\first_dataset.xlsx', sheet_name="customers", engine="openpyxl")
print("Dataset loaded successfully.", '\n')

# Deep copy of Dataset
df = data.copy(deep=True)
print('Create deep copy of dataset for data cleaning', '\n')

Dataset loaded successfully.

Create deep copy of dataset for data cleaning

In [5]:
# بررسی و اصلاح نام ستون ها

df.columns = (df.columns.astype(str).str.strip().str.lower()
              .str.replace(r"[\s\-]+", "_", regex=True).str.replace(r"[^\w_]", "", regex=True))

# ۱. ذخیره نام‌های اولیه ستون‌ها
original_columns = df.columns.astype(str)

# ۲. ساخت نام‌های تمیز و استاندارد
cleaned_columns = (original_columns.str.strip().str.lower().str.replace(r"[\s\-]+", "_", regex=True)
    .str.replace(r"[^\w_]", "", regex=True))

# ۳. شناسایی ستون‌هایی که دچار تغییر شده‌اند (Mask)
changed_mask = original_columns != cleaned_columns

# ۴. ساخت جدول گزارش ممیزی
column_audit_report = pd.DataFrame({
        "original_name": original_columns[changed_mask],
        "cleaned_name": cleaned_columns[changed_mask],})

# ۵. اعمال نام‌های تمیز روی دیتافریم
df.columns = cleaned_columns

# ۶. نمایش خلاصه گزارش
total_changed = changed_mask.sum()

if total_changed > 0:
    print(f"⚠️ تعداد {total_changed} ستون غیراستاندارد شناسایی و اصلاح شدند:\n")
    display(column_audit_report)
else:
    print("✅ تمام نام ستون‌ها از ابتدا کاملاً استاندارد و تمیز بودند.")

✅ تمام نام ستون‌ها از ابتدا کاملاً استاندارد و تمیز بودند.

In [6]:
df.head(3)

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     object
 2   gender              61 non-null     object
 3   age                 60 non-null     float64
 4   city                61 non-null     object
 5   province            61 non-null     object
 6   signup_date         61 non-null     object
 7   membership_tier     61 non-null     object
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     object
 13  device              61 non-null     object
 14  discount_used       61 non-null     object
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), object(9)
memory usage: 8.2+ KB

In [8]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,61.0,NaN,NaN,NaN,1030.229508,17.446483,1001.0,1015.0,1030.0,1045.0,1060.0
first_name,61,12,Reza,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,61,2,F,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,60.0,NaN,NaN,NaN,45.2,19.167239,19.0,31.75,45.0,58.0,145.0
city,61,8,Tabriz,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
province,61,8,East Azerbaijan,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
signup_date,61,58,2021-11-08,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
membership_tier,61,4,Gold,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
purchase_count,61.0,NaN,NaN,NaN,17.606557,10.214824,0.0,11.0,17.0,26.0,35.0
avg_order_value,61.0,NaN,NaN,NaN,211.435738,130.113726,27.63,108.19,161.33,323.32,449.81
total_spending,60.0,NaN,NaN,NaN,3749.667333,4262.248522,0.0,1167.035,2188.865,4692.15,25000.0
last_purchase_days,61.0,NaN,NaN,NaN,196.934426,97.892436,3.0,132.0,201.0,273.0,365.0
payment_method,61,3,Online Wallet,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device,61,3,Android,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount_used,61,2,No,35,NaN,NaN,NaN,NaN,NaN,NaN,NaN
returned_items,61.0,NaN,NaN,NaN,4.196721,2.663454,0.0,2.0,4.0,7.0,8.0
satisfaction_score,61.0,NaN,NaN,NaN,3.0,1.42595,1.0,2.0,3.0,4.0,5.0

In [9]:
# Columns in Dataset

print('Columns in Dataset')
print(15*'=')
for index, column in enumerate(df.columns, start=1) :
    print(f'{index:02d}. {column}')
print('\n'*2)


print('Number of Features & Records')
print(28*'=')
print(f'Number of Featuers is : {df.shape[0]}')
print(f'Number of Records is : {df.shape[1]}')

Columns in Dataset
===============
01. customer_id
02. first_name
03. gender
04. age
05. city
06. province
07. signup_date
08. membership_tier
09. purchase_count
10. avg_order_value
11. total_spending
12. last_purchase_days
13. payment_method
14. device
15. discount_used
16. returned_items
17. satisfaction_score



Number of Features & Records
============================
Number of Featuers is : 61
Number of Records is : 17

In [10]:
summary_table = pd.DataFrame({
    'column_name' : df.columns,
    'dtypes' : df.dtypes.values,
    'value_counts' : df.notna().sum().values,
    'Missing_count' : df.isna().sum().values,
    'Missing_Percentage' : ((df.isna().mean()*100).round(2)).values,
    'Unique_count' : df.nunique(dropna=False).values,
    'Min' : df.min().values,
    'Max' : df.max().values})

display(summary_table)

# Save as excel
import pandas as pd

excel_filename = r"F:\StudyBuilt\dataset_summary_audit.xlsx"

# ذخیره با موتور openpyxl و استایل‌دهی خودکار
with pd.ExcelWriter(excel_filename, engine="openpyxl") as writer:
    summary_table.to_excel(writer, sheet_name="Data_Audit_Summary", index=False)

    # دسترسی به شیت ساخته‌شده برای تنظیمات ظاهری
    worksheet = writer.sheets["Data_Audit_Summary"]

    # فریز کردن ردیف اول (Header)
    worksheet.freeze_panes = "A2"

    # تنظیم خودکار عرض ستون‌ها بر اساس طول محتوا + مقداری فاصله
    for col in worksheet.columns:
        max_len = max(len(str(cell.value or "")) for cell in col)
        col_letter = col[0].column_letter
        worksheet.column_dimensions[col_letter].width = max(max_len + 4, 12)

print(f"🚀 Summary Table Saved to This path :    '{excel_filename}'")

,column_name,dtypes,value_counts,Missing_count,Missing_Percentage,Unique_count,Min,Max
0,customer_id,int64,61,0,0.00,60,1001,1060
1,first_name,object,61,0,0.00,12,Ali,Zahra
2,gender,object,61,0,0.00,2,F,M
3,age,float64,60,1,1.64,35,19.0,145.0
4,city,object,61,0,0.00,8,Ahvaz,Tehran
5,province,object,61,0,0.00,8,Alborz,Tehran
6,signup_date,object,61,0,0.00,58,2021-02-23,2025-09-09
7,membership_tier,object,61,0,0.00,4,Bronze,VIP
8,purchase_count,int64,61,0,0.00,30,0,35
9,avg_order_value,float64,61,0,0.00,60,27.63,449.81
10,total_spending,float64,60,1,1.64,60,0.0,25000.0
11,last_purchase_days,int64,61,0,0.00,54,3,365
12,payment_method,object,61,0,0.00,3,Card,Online Wallet
13,device,object,61,0,0.00,3,Android,iPhone
14,discount_used,object,61,0,0.00,2,No,Yes
15,returned_items,int64,61,0,0.00,9,0,8
16,satisfaction_score,int64,61,0,0.00,5,1,5

🚀 Summary Table Saved to This path :    'F:\StudyBuilt\dataset_summary_audit.xlsx'

In [11]:
# Separating Columns by Dtype

columns_types = summary_table.groupby('dtypes')['column_name'].apply(list)
columns_types

for dtype, columns in columns_types.items():
    print(f'{dtype}')
    for column in columns:
        print(f' - {column}')
    print()

int64
 - customer_id
 - purchase_count
 - last_purchase_days
 - returned_items
 - satisfaction_score

float64
 - age
 - avg_order_value
 - total_spending

object
 - first_name
 - gender
 - city
 - province
 - signup_date
 - membership_tier
 - payment_method
 - device
 - discount_used

In [12]:
# Column Segregation by Data Type

numeric_columns = df.select_dtypes(include="number").columns.tolist()
text_columns = df.select_dtypes(include=["object", "string"]).columns.tolist()
datetime_columns = df.select_dtypes(include=["datetime", "datetimetz"]).columns.tolist()

print("Numeric columns:")
print(numeric_columns)

print("\nText columns:")
print(text_columns)

print("\nDatetime columns:")
print(datetime_columns)

Numeric columns:
['customer_id', 'age', 'purchase_count', 'avg_order_value', 'total_spending', 'last_purchase_days', 'returned_items', 'satisfaction_score']

Text columns:
['first_name', 'gender', 'city', 'province', 'signup_date', 'membership_tier', 'payment_method', 'device', 'discount_used']

Datetime columns:
[]

## 3. Data Cleaning

### Data Type

In [13]:
# Data Type Correction

df['gender'] = df['gender'].astype('string')

df['age'] = (pd.to_numeric(df['age'],errors='coerce').astype('Int64'))

df['city'] = df['city'].astype('string')

df['signup_date'] = pd.to_datetime(df['signup_date'], format='%Y-%m-%d', errors='coerce')

df['membership_tier'] = df['membership_tier'].astype('string')

df['payment_method'] = df['payment_method'].astype('string')

df['device'] = df['device'].astype('string')

df['discount_used'] = df['discount_used'].astype('string')

In [14]:
# Separating Columns by Dtype

columns_types = summary_table.groupby('dtypes')['column_name'].apply(list)
columns_types

for dtype, columns in columns_types.items():
    print(f'{dtype}')
    for column in columns:
        print(f' - {column}')
    print()

int64
 - customer_id
 - purchase_count
 - last_purchase_days
 - returned_items
 - satisfaction_score

float64
 - age
 - avg_order_value
 - total_spending

object
 - first_name
 - gender
 - city
 - province
 - signup_date
 - membership_tier
 - payment_method
 - device
 - discount_used

In [15]:
# COLUMN SEGREGATION BY DATA TYPE

# 1. Numeric columns
numeric_columns = df.select_dtypes(include=["number"]).columns.tolist()

# 2. Text columns
text_columns = df.select_dtypes(include=["object", "string"]).columns.tolist()

# 3. Datetime columns
datetime_columns = df.select_dtypes(include=["datetime64", "datetimetz"]).columns.tolist()

# 4. Boolean columns
boolean_columns = df.select_dtypes(include=["bool", "boolean"]).columns.tolist()

# 5. Categorical columns
categorical_columns = df.select_dtypes(include=["category"]).columns.tolist()

# بررسی ستون‌هایی که هنوز در هیچ گروهی قرار نگرفته‌اند
classified_columns = set(
    numeric_columns
    + text_columns
    + datetime_columns
    + boolean_columns
    + categorical_columns)

unclassified_columns = [column for column in df.columns if column not in classified_columns]

# نمایش نتایج
print("Numeric columns:")
print(numeric_columns)

print("\nText columns:")
print(text_columns)

print("\nDatetime columns:")
print(datetime_columns)

print("\nBoolean columns:")
print(boolean_columns)

print("\nCategorical columns:")
print(categorical_columns)

print("\nUnclassified columns:")
print(unclassified_columns)

Numeric columns:
['customer_id', 'age', 'purchase_count', 'avg_order_value', 'total_spending', 'last_purchase_days', 'returned_items', 'satisfaction_score']

Text columns:
['first_name', 'gender', 'city', 'province', 'membership_tier', 'payment_method', 'device', 'discount_used']

Datetime columns:
['signup_date']

Boolean columns:
[]

Categorical columns:
[]

Unclassified columns:
[]

In [16]:
# column_type_summary

column_type_summary = pd.DataFrame({
    "column_name": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "data_type_group": [("numeric"
            if column in numeric_columns
            else "text"
            if column in text_columns
            else "datetime"
            if column in datetime_columns
            else "unclassified")
        for column in df.columns]})

display(column_type_summary)

           column_name           dtype data_type_group
0          customer_id           int64         numeric
1           first_name          object            text
2               gender          string            text
3                  age           Int64         numeric
4                 city          string            text
5             province          object            text
6          signup_date  datetime64[ns]        datetime
7      membership_tier          string            text
8       purchase_count           int64         numeric
9      avg_order_value         float64         numeric
10      total_spending         float64         numeric
11  last_purchase_days           int64         numeric
12      payment_method          string            text
13              device          string            text
14       discount_used          string            text
15      returned_items           int64         numeric
16  satisfaction_score           int64         numeric

### Duplicate

In [17]:
# Duplicate Record Analysis

print(f'Duplicate Record Analysis')
print('---------------------------', '\n')

exact_duplicate = df.duplicated().sum()
print(f'Number of exact duplicate rows : {exact_duplicate}')

duplicate_rows = df[df.duplicated(keep=False)]
print(f'Number of rows involved in exact duplication : {len(duplicate_rows)}', '\n')

print(f'Display Duplicated Rows :','\n')
display(duplicate_rows)

Duplicate Record Analysis
---------------------------

Number of exact duplicate rows : 1
Number of rows involved in exact duplication : 2

Display Duplicated Rows :

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [18]:
# duplicate_id_analysis

duplicate_id_analysis = []

for customer_id, group in duplicate_rows.groupby("customer_id"):
    duplicate_id_analysis.append({
        "customer_id": customer_id,
        "record_count": len(group),
        "all_rows_identical": (group.drop(columns="customer_id").drop_duplicates().shape[0] == 1)})

duplicate_id_analysis_df = pd.DataFrame(duplicate_id_analysis)
display(duplicate_id_analysis_df)

   customer_id  record_count  all_rows_identical
0         1014             2                True

### String Column Quality Assessment

In [19]:
# Text columns

print(f"Number of text columns: {len(text_columns)}")

for column in text_columns:
    print(f"- {column}")

Number of text columns: 8
- first_name
- gender
- city
- province
- membership_tier
- payment_method
- device
- discount_used

In [20]:
# Text_Quality_Summary

text_quality_summary = []

for column in text_columns:
    # تضمین تایپ رشته‌ای
    text_series = df[column].astype("string")

    # ۱. شروع با هرگونه فضای خالی (اسپیس، تب، اینتر)
    leading_space_count = int(text_series.str.contains(r"^\s", regex=True, na=False).sum())

    # ۲. پایان با هرگونه فضای خالی
    trailing_space_count = int(text_series.str.contains(r"\s$", regex=True, na=False).sum())

    # ۳. فاقد محتوای معنادار (صرفاً فاصله‌ خالی یا پوچ)
    whitespace_only_count = int(text_series.str.strip().eq("").sum())

    text_quality_summary.append({
        "column_name": column,
        "leading_space_count": leading_space_count,
        "trailing_space_count": trailing_space_count,
        "whitespace_only_count": whitespace_only_count,})

text_quality_summary_df = pd.DataFrame(text_quality_summary)
display(text_quality_summary_df)


text_columns_with_issues = text_quality_summary_df.loc[(text_quality_summary_df[[
"leading_space_count","trailing_space_count","whitespace_only_count"]].sum(axis=1) > 0)].copy()

if text_columns_with_issues.empty:
    print("No whitespace or blank-string issues were detected.")
else:
    display(text_columns_with_issues)


total_text_issues = int(text_quality_summary_df[["leading_space_count","trailing_space_count","whitespace_only_count"]].sum().sum())
print(f"Total detected text-format issues: {total_text_issues}")

,column_name,leading_space_count,trailing_space_count,whitespace_only_count
0,first_name,0,0,0
1,gender,0,0,0
2,city,0,0,0
3,province,0,0,0
4,membership_tier,0,0,0
5,payment_method,0,0,0
6,device,0,0,0
7,discount_used,0,0,0

No whitespace or blank-string issues were detected.
Total detected text-format issues: 0

### Categorical Column Quality Assessment

In [21]:
categorical_columns = ["gender","city","province","membership_tier","payment_method","device","discount_used"]
print("Categorical columns selected for inspection:")
for column in categorical_columns:
    print(f"- {column}")

Categorical columns selected for inspection:
- gender
- city
- province
- membership_tier
- payment_method
- device
- discount_used

In [22]:
# Categorical Column Analysis

for column in categorical_columns:
    print("\n" + "=" * 60)
    print(f"Column: {column}")
    print("=" * 60)
    category_counts = (df[column].value_counts(dropna=False).rename_axis("category").reset_index(name="count") )
    category_counts["percentage"] = (category_counts["count"]/ len(df) * 100 ).round(2)
    display(category_counts)
    print(f'Cardinality of {column} is : {df[column].nunique(dropna=True)}')
    print(f'Missing count of {column} is : {df[column].isna().sum()}')
    print(f'Percentage of missing value is : {(df[column].isna().mean()*100).round(2)}')

============================================================
Column: gender
============================================================

  category  count  percentage
0        F     35       57.38
1        M     26       42.62

Cardinality of gender is : 2
Missing count of gender is : 0
Percentage of missing value is : 0.0

============================================================
Column: city
============================================================

  category  count  percentage
0   Tabriz     13       21.31
1  Mashhad     11       18.03
2    Ahvaz      8       13.11
3    Karaj      7       11.48
4   Tehran      6        9.84
5   Shiraz      6        9.84
6  Isfahan      5         8.2
7    Rasht      5         8.2

Cardinality of city is : 8
Missing count of city is : 0
Percentage of missing value is : 0.0

============================================================
Column: province
============================================================

          category  count  percentage
0  East Azerbaijan     13       21.31
1         Khorasan     11       18.03
2        Khuzestan      8       13.11
3           Alborz      7       11.48
4           Tehran      6        9.84
5             Fars      6        9.84
6          Isfahan      5        8.20
7            Gilan      5        8.20

Cardinality of province is : 8
Missing count of province is : 0
Percentage of missing value is : 0.0

============================================================
Column: membership_tier
============================================================

  category  count  percentage
0     Gold     19       31.15
1   Bronze     18       29.51
2      VIP     16       26.23
3   Silver      8       13.11

Cardinality of membership_tier is : 4
Missing count of membership_tier is : 0
Percentage of missing value is : 0.0

============================================================
Column: payment_method
============================================================

        category  count  percentage
0  Online Wallet     23        37.7
1           Card     19       31.15
2           Cash     19       31.15

Cardinality of payment_method is : 3
Missing count of payment_method is : 0
Percentage of missing value is : 0.0

============================================================
Column: device
============================================================

  category  count  percentage
0  Android     23        37.7
1      Web     20       32.79
2   iPhone     18       29.51

Cardinality of device is : 3
Missing count of device is : 0
Percentage of missing value is : 0.0

============================================================
Column: discount_used
============================================================

  category  count  percentage
0       No     35       57.38
1      Yes     26       42.62

Cardinality of discount_used is : 2
Missing count of discount_used is : 0
Percentage of missing value is : 0.0

### Date Column Quality Assessment

In [23]:
print("Sample signup_date values:")
display(df[["customer_id", "signup_date"]].head(10))

Sample signup_date values:

   customer_id signup_date
0         1001  2025-02-19
1         1002  2022-08-19
2         1003  2023-06-20
3         1004  2021-11-08
4         1005  2021-10-21
5         1006  2022-01-26
6         1007  2025-09-09
7         1008  2024-10-03
8         1009  2021-05-14
9         1010  2022-06-25

In [24]:
date_format_pattern = r"^\d{4}-\d{2}-\d{2}$"

date_format_mask = (df["signup_date"].astype("string").str.match(date_format_pattern, na=False))

valid_format_count = int(date_format_mask.sum())
invalid_format_count = int((~date_format_mask).sum())
print(f"Dates matching YYYY-MM-DD format: {valid_format_count}")
print(f"Dates with a different format   : {invalid_format_count}")

invalid_format_rows = df.loc[~date_format_mask,["customer_id", "signup_date"]].copy()
if invalid_format_rows.empty:
    print("All signup dates follow the YYYY-MM-DD format.")
else:
    display(invalid_format_rows)



parsed_signup_date = pd.to_datetime(df["signup_date"],format="%Y-%m-%d",errors="coerce")
invalid_date_mask = parsed_signup_date.isna()
invalid_date_count = int(invalid_date_mask.sum())
invalid_date_rows = df.loc[invalid_date_mask,["customer_id", "signup_date"]].copy()

if invalid_date_rows.empty:
    print("All signup dates were parsed successfully.")
else:
    display(invalid_date_rows)
print(f"Number of invalid dates: {invalid_date_count}")

Dates matching YYYY-MM-DD format: 61
Dates with a different format   : 0
All signup dates follow the YYYY-MM-DD format.
All signup dates were parsed successfully.
Number of invalid dates: 0

In [25]:
# start and end date

print(f"Earliest signup date: {parsed_signup_date.min().date()}")
print(f"Latest signup date  : {parsed_signup_date.max().date()}")

Earliest signup date: 2021-02-23
Latest signup date  : 2025-09-09

In [26]:
# تبدیل تاریخ‌ها
#parsed_signup_date = pd.to_datetime(df["signup_date"],errors="coerce")

# تعداد مقادیر غیرخالی اولیه
non_missing_date_count = int(df["signup_date"].notna().sum())

# تعداد تاریخ‌های قابل تبدیل
valid_date_count = int(parsed_signup_date.notna().sum())

# تعداد تاریخ‌های نامعتبر یا غیرقابل تبدیل
invalid_date_count = int(parsed_signup_date.isna().sum())

# تاریخ‌های آینده
today = pd.Timestamp.today().normalize()

future_date_mask = parsed_signup_date > today
future_date_count = int(future_date_mask.sum())

# بررسی فرمت ظاهری مورد انتظار: YYYY-MM-DD
raw_signup_date = df["signup_date"].astype("string")

expected_format_mask = raw_signup_date.str.fullmatch(r"\d{4}-\d{2}-\d{2}",na=False)

matching_expected_format_count = int(expected_format_mask.sum())

different_format_count = int((~expected_format_mask & raw_signup_date.notna()).sum())

# تعداد تاریخ‌های یکتا و معتبر
unique_date_count = int(parsed_signup_date.nunique(dropna=True))

# ساخت گزارش
date_validation_summary = pd.DataFrame({
"metric": ["total_records","non_missing_dates","valid_parsed_dates","matching_expected_format","different_format","invalid_dates",
           "future_dates","unique_valid_dates"],
"value": [len(df),non_missing_date_count,valid_date_count,matching_expected_format_count,different_format_count,invalid_date_count,
future_date_count,unique_date_count]})
display(date_validation_summary)

                     metric  value
0             total_records     61
1         non_missing_dates     61
2        valid_parsed_dates     61
3  matching_expected_format     61
4          different_format      0
5             invalid_dates      0
6              future_dates      0
7        unique_valid_dates     58

### Numeric Column Quality Assessment

In [27]:
numeric_profile = df[numeric_columns].describe().T

numeric_profile["missing_count"] = (df[numeric_columns].isna().sum())
numeric_profile["unique_count"] = (df[numeric_columns].nunique(dropna=True))
numeric_profile["zero_count"] = (df[numeric_columns].eq(0).sum())
numeric_profile["negative_count"] = (df[numeric_columns].lt(0).sum())

display(numeric_profile)

,count,mean,std,min,25%,50%,75%,max,missing_count,unique_count,zero_count,negative_count
customer_id,61.0,1030.229508,17.446483,1001.0,1015.0,1030.0,1045.0,1060.0,0,60,0,0
age,60.0,45.2,19.167239,19.0,31.75,45.0,58.0,145.0,1,34,0,0
purchase_count,61.0,17.606557,10.214824,0.0,11.0,17.0,26.0,35.0,0,30,1,0
avg_order_value,61.0,211.435738,130.113726,27.63,108.19,161.33,323.32,449.81,0,60,0,0
total_spending,60.0,3749.667333,4262.248522,0.0,1167.035,2188.865,4692.15,25000.0,1,59,1,0
last_purchase_days,61.0,196.934426,97.892436,3.0,132.0,201.0,273.0,365.0,0,54,0,0
returned_items,61.0,4.196721,2.663454,0.0,2.0,4.0,7.0,8.0,0,9,6,0
satisfaction_score,61.0,3.0,1.42595,1.0,2.0,3.0,4.0,5.0,0,5,0,0

In [28]:
# 

def find_non_numeric(df, columns=numeric_columns):
    if columns is None:
        columns = df.columns
    
    results = {}
    
    for col in columns:
        converted = pd.to_numeric(df[col], errors='coerce')
        
        new_na = converted.isna()        # بعد از تبدیل NaN شده
        original_na = df[col].isna()     # از اول NaN بوده
        
        problematic_mask = new_na & ~original_na  # فقط اون‌هایی که ما باعث NaN شدیم
        
        if problematic_mask.any():
            results[col] = df[col][problematic_mask]
    
    return results


# استفاده:
non_numeric = find_non_numeric(df)

for col, values in non_numeric.items():
    print(f"\nستون '{col}':")
    print(f"  تعداد مقادیر غیر عددی: {len(values)}")
    print(f"  مقادیر منحصر به فرد: {values.unique()}")
    print(f"  ایندکس‌ها: {values.index.tolist()}")


non_numeric = find_non_numeric(df, columns=numeric_columns)
non_numeric

{}

### Cross-Column Consistency & Business Logic Validation

In [29]:
df[numeric_columns].describe(include='all').T

,count,mean,std,min,25%,50%,75%,max
customer_id,61.0,1030.229508,17.446483,1001.0,1015.0,1030.0,1045.0,1060.0
age,60.0,45.2,19.167239,19.0,31.75,45.0,58.0,145.0
purchase_count,61.0,17.606557,10.214824,0.0,11.0,17.0,26.0,35.0
avg_order_value,61.0,211.435738,130.113726,27.63,108.19,161.33,323.32,449.81
total_spending,60.0,3749.667333,4262.248522,0.0,1167.035,2188.865,4692.15,25000.0
last_purchase_days,61.0,196.934426,97.892436,3.0,132.0,201.0,273.0,365.0
returned_items,61.0,4.196721,2.663454,0.0,2.0,4.0,7.0,8.0
satisfaction_score,61.0,3.0,1.42595,1.0,2.0,3.0,4.0,5.0

In [30]:
# ۱. تعریف قوانین خطا (همون دیکشنری قبلی)
validation_rules = {
    'age_invalid': (df['age'].le(0) | df['age'].gt(120)),
    'spending_invalid': (df['total_spending'].gt(15000)),
    'purchase_invalid': (df['purchase_count'].lt(0))
}

# ۲. ساخت دیتافریمِ پرچم‌های خطا
validation_df = pd.DataFrame(validation_rules)

# ۳. استخراج رکوردهای دارای مشکل از دیتافریم اصلی (df)
# متد any(axis=1) چک میکنه که آیا در هر سطر، حتی یکی از ستون‌ها True (خطا) هست یا نه
error_rows = df[validation_df.any(axis=1)]

# ۴. نمایش تعداد و خودِ رکوردها
print(f"تعداد رکوردهای دارای مشکل: {len(error_rows)}")
print("\nنمایش رکوردهای مشکل‌دار:")
display(error_rows)  # اگر توی ژوپیتر هستی از display استفاده کن، وگرنه print(error_rows)


# این کد بهت نشون میده در رکوردهای خراب، کدوم ستون‌ها True شدن
print(validation_df[validation_df.any(axis=1)].query("age_invalid | spending_invalid | purchase_invalid"))

تعداد رکوردهای دارای مشکل: 2

نمایش رکوردهای مشکل‌دار:

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.00,340,Cash,Web,Yes,4,4

    age_invalid  spending_invalid  purchase_invalid
9          True             False             False
29        False              True             False

#### age

In [31]:
# 1) پیدا کردن ردیف‌های مشکوک
invalid_age_index = df.index[df['age'] > 100]

# 2) ذخیره رکوردها قبل از تغییر
invalid_age_rows_before = df.loc[invalid_age_index].copy()

# 3) تبدیل سن نامعتبر به مقدار گمشده
df.loc[invalid_age_index, 'age'] = np.nan

# 4) دیدن رکوردها بعد از تغییر
invalid_age_rows_after = df.loc[invalid_age_index].copy()

display(invalid_age_rows_before)
display(invalid_age_rows_after)

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,<NA>,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [32]:
# fill
df['age'] = df['age'].fillna(df['age'].mean().round())
df['age'].isna().sum()
print(df.loc[9])

customer_id                          1010
first_name                          Arash
gender                                  F
age                                    44
city                                Karaj
province                           Alborz
signup_date           2022-06-25 00:00:00
membership_tier                    Silver
purchase_count                         19
avg_order_value                    381.13
total_spending                    7241.47
last_purchase_days                    276
payment_method              Online Wallet
device                            Android
discount_used                          No
returned_items                          7
satisfaction_score                      1
Name: 9, dtype: object

#### Total_spending

In [33]:
# ۱. محاسبه مقدار مورد انتظار
expected = df['purchase_count'] * df['avg_order_value']

# ۲. ایجاد ماسک بولی
mask = (df['total_spending'] - expected).abs() > 0.01

# ۳. استخراج ردیف‌های دارای مغایرت بدون تغییر در df
mismatched_rows = df[mask]
mismatched_rows

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4

In [34]:
# 1) پیدا کردن ردیف‌های مشکوک
invalid_total_index = df.index[df['total_spending'] == 25000]

# 2) ذخیره رکوردها قبل از تغییر
invalid_total_rows_before = df.loc[invalid_total_index].copy()

# 3) تبدیل سن نامعتبر به مقدار گمشده
df.loc[invalid_total_index, 'total_spending'] = np.nan

# 4) دیدن رکوردها بعد از تغییر
invalid_total_rows_after = df.loc[invalid_total_index].copy()

display(invalid_total_rows_before)
display(invalid_total_rows_after)

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.0,340,Cash,Web,Yes,4,4

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,NaN,340,Cash,Web,Yes,4,4

In [35]:
df[df['total_spending'].isnull()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
29,1030,Sina,M,60,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,NaN,340,Cash,Web,Yes,4,4
39,1040,Amir,F,65,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [36]:
# fill by "purchase_count*avg_order_value
df['total_spending'] = df['total_spending'].fillna(df['purchase_count'] * df['avg_order_value'])

In [37]:
row1 = df.loc[28]
print(row1, '\n')
print('-----------------------------------------------------', '\n')
row2 = df.loc[38]
print(row2)

customer_id                          1029
first_name                            Ali
gender                                  F
age                                    34
city                               Tabriz
province                  East Azerbaijan
signup_date           2023-07-03 00:00:00
membership_tier                      Gold
purchase_count                          2
avg_order_value                    323.32
total_spending                     646.64
last_purchase_days                    319
payment_method                       Cash
device                                Web
discount_used                         Yes
returned_items                          4
satisfaction_score                      5
Name: 28, dtype: object

-----------------------------------------------------

customer_id                          1039
first_name                          Parsa
gender                                  M
age                                    47
city                               Shiraz
province                             Fars
signup_date           2022-08-11 00:00:00
membership_tier                      Gold
purchase_count                         11
avg_order_value                     36.87
total_spending                     405.57
last_purchase_days                    194
payment_method                       Cash
device                             iPhone
discount_used                          No
returned_items                          1
satisfaction_score                      4
Name: 38, dtype: object

#### purchase_count & returned_items

In [38]:
invalid_returns = df[(df['returned_items'] > df['purchase_count']) | (df['returned_items'] < 0) | (df['purchase_count'] < 0)]
invalid_returns
invalid_summary = invalid_returns[['purchase_count', 'returned_items']]
invalid_summary

    purchase_count  returned_items
7                3               8
14               3               8
23               0               2
28               2               4
36               1               7
55               1               4

In [39]:
# ۱. بخش فلگ‌گذاری (Flagging)
# شرط: تعداد مرجوعی بیشتر از تعداد خرید باشد یا مقادیر منفی باشند
df['needs_review'] = (df['returned_items'] > df['purchase_count']) | (df['returned_items'] < 0) | (df['purchase_count'] < 0)
display(df)

# ستون دلیل برای گزارش شفاف به مدیر
df['review_reason'] = 'Approved'
df.loc[df['returned_items'] > df['purchase_count'], 'review_reason'] = 'Flag: Return count exceeds Purchase count'
df.loc[(df['returned_items'] < 0) | (df['purchase_count'] < 0), 'review_reason'] = 'Flag: Negative count detected'


# ۲. خروجی گرفتن برای مدیر (Export)
# فقط ردیف‌هایی که نیاز به بررسی دارند را فیلتر کرده و ذخیره می‌کنیم
manager_report = df[df['needs_review'] == True]

print(f"تعداد ردیف‌های مغایر ارسال‌شده به گزارش: {len(manager_report)}")

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score,needs_review
0,1001,Reza,F,19,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5,False
1,1002,Sina,M,53,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3,False
2,1003,Parsa,F,31,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1,False
3,1004,Sina,F,58,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4,False
4,1005,Kimia,M,28,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Maryam,M,58,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4,False
57,1058,Amir,F,47,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2,False
58,1059,Ali,F,57,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5,False
59,1060,Ali,M,63,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3,False
60,1014,Reza,M,35,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4,False

 شیت 'Sheet1' با موفقیت ذخیره شد.
تعداد ردیف‌های مغایر ارسال‌شده به گزارش: 6

#### Name & Gender

In [40]:
name_gender_dict = { 'Neda' : 'F',
               'Ali' : 'M',
               'Sina' : 'M',
               'Reza' : 'M',
               'Kimia' : 'F',
               'Amir' : 'M',
               'Parsa' : 'M',
               'Maryam' : 'F',
               'Mina' : 'F',
               'Arash' : 'M',
               'Zahra' : 'F',
               'Sara' :'F'}

In [41]:
# ۱. پیدا کردن جنسیت مورد انتظار از روی دیکشنری
expected_gender = df['first_name'].map(name_gender_dict)

# ۲. ایجاد ماسک: سطرهایی که در دیکشنری وجود دارند ولی جنسیت فعلی با دیکشنری فرق دارد
changed_mask = expected_gender.notna() & (df['gender'] != expected_gender)

# ۳. استخراج گزارش تغییرات (Audit Report)
changed_report = df.loc[changed_mask, ['first_name', 'gender']].copy()
changed_report['old_gender'] = changed_report['gender']
changed_report['new_gender'] = expected_gender[changed_mask]

# حذف ستون اضافه و مرتب‌سازی ستون‌ها برای شفافیت
changed_report = changed_report[['first_name', 'old_gender', 'new_gender']]

# ۴. حالا تغییرات را روی دیتای اصلی اعمال می‌کنیم
df.loc[changed_mask, 'gender'] = expected_gender[changed_mask]

# ۵. خروجی گزارش تغییرات برای ذخیره یا بازبینی مدیر
print(f"تعداد کل رکوردهای اصلاح‌شده: {len(changed_report)}")
print(changed_report.head())

تعداد کل رکوردهای اصلاح‌شده: 38
  first_name old_gender new_gender
0       Reza          F          M
2      Parsa          F          M
3       Sina          F          M
4      Kimia          M          F
5       Amir          F          M
 شیت 'Sheet2' با موفقیت ذخیره شد.

In [42]:
df[df['gender'] == 'F'].value_counts().sum() + df[df['gender'] == 'M'].value_counts().sum()

np.int64(61)

### missing values

In [43]:
df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
needs_review          0
review_reason         0
dtype: int64

### Save to Excel

In [44]:
cleaned_dataset_githubusername = df.to_excel(r'F:\StudyBuilt\ali-ashrafi\data\processed\cleaned_dataset_ali_ashrafi.xlsx', index=False)